In [1]:
import tensorflow as tf
import pandas as pd

In [2]:
# 데이터 호출\
filename = "iris.csv"
data_raw = pd.read_csv(filename)

# 범주형 데이터이기 때문에 원핫 인코딩으로 진행 --> 각 종속 변수를 분리하여 0, 1로 분류
data = pd.get_dummies(data_raw)

# 범주의 분류 구하기
# data_raw['품종'].value_counts()

In [3]:
# 데이터 세팅
# iloc 와 미묘한 차이가 있다
iv = data[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dv = data[['품종_setosa', '품종_versicolor', '품종_virginica']]

In [4]:
# 비율 예측을 위해 활성화함수 softmax 사용
#  0 <= softmax() <= 1
X = tf.keras.layers.Input(shape=[4]) # 4개의 input

# hidden layer 추가
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)

Y = tf.keras.layers.Dense(3, activation="softmax")(H) # 3개의 범주
model = tf.keras.models.Model(X, Y)
model.compile(loss="categorical_crossentropy", metrics='accuracy')

In [5]:
model.fit(iv, dv, epochs=10000, verbose=0)
model.fit(iv, dv, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0393 - accuracy: 0.9867
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0376 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0396 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0345 - accuracy: 0.9867
Epoch 5/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0392 - accuracy: 0.9867
Epoch 6/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0377 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0372 - accuracy: 0.9867
Epoch 8/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0344 - accuracy: 0.9867
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0355 - accuracy: 0.9933
Epoch 10/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0367 - accuracy: 0.9800


In [6]:
print(model.predict(iv[:5]))
print(dv[:5])

[[1.0000000e+00 1.0090965e-09 0.0000000e+00]
 [1.0000000e+00 1.0912698e-10 0.0000000e+00]
 [1.0000000e+00 6.1680361e-10 3.0098386e-38]
 [1.0000000e+00 6.7045275e-10 4.8272647e-37]
 [1.0000000e+00 3.9822865e-09 0.0000000e+00]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [7]:
# 모델의 가중치 확인
model.get_weights()

[array([[-0.33153394,  0.855035  ,  0.5284237 , -0.1302876 ,  0.336131  ,
         -0.31537363,  0.08174673,  0.2424683 ],
        [-0.17024192,  0.43322232,  0.54378176, -0.17503195, -0.66509837,
          0.6367806 , -0.4589806 ,  0.36759955],
        [ 1.0362544 , -0.17194067, -0.5967825 , -0.15487297,  0.5043281 ,
         -0.30259016, -0.373885  ,  0.19447707],
        [ 0.5820652 , -1.0156561 , -0.68861496, -0.59519047,  1.0008191 ,
         -0.9802461 , -0.41277727,  0.7173562 ]], dtype=float32),
 array([-0.18070608,  0.37839583,  0.4318429 ,  0.51822275, -0.5728705 ,
         0.5475475 ,  0.5212719 , -0.70213956], dtype=float32),
 array([[-1.0392116 , -0.5026315 ,  0.75665903, -0.8611477 , -0.2932031 ,
         -0.11139487, -0.6760767 ,  0.11422287],
        [ 0.31221193,  0.33138406, -0.38476974,  0.38924608,  0.27112824,
         -0.8315502 ,  0.46161503, -0.19894639],
        [ 1.1689904 ,  0.56319743, -1.4933003 ,  0.9588696 ,  0.2564915 ,
         -0.8757693 , -0.03700118,